### ISSUE TITLE
svdrp4j stdanalone bzw. in jcenter 

### ISSUE THREAD

**Issue by herrlado** [hampelratte/svdrp4j#3]
Here the story.
I use svdrp4j in vdr-manager, which is an android app. I'd like thisi app to be included in f-droid repository.
f-droid peaople would like to have alls the dependencies in jcenter or central or jitpack

https://gitlab.com/fdroid/fdroiddata/merge_requests/1290

The svdrp4j is the only dependency which is not there. I have made release 1.1.0 in my fork and then uploaded to bintray (jcenter hoster)
https://bintray.com/herrlado/herrlado/org.hampelratte.svdrp4j/view

The Problem is now parent pom is not in bintray. So can we just make svdrp4j a stanalone project and shoud I manage the publishing the releases to the bintray?

Lado

**Comment by hampelratte** [comment]
1. You could have asked beforehand
2. You didn't respect the license by releasing a new version without my permission and relicensing it. This feels like a hostile takeover.
3. The guy from fdroid asked if the dependencies are in a public repository OR can be built from source, which is clearly the case for svdrp4j. So you didn't even need to do all that.

That said, I'm willing to release a version 1.1.0. I'm not going to change the pom, since the parent pom is also publicly available: http://www.hampelratte.org/maven/releases/org/hampelratte/parent/9/

I'm also going to file a report at jfrog to remove the version you released, because I don't want it to be hosted there.

**Comment by herrlado** [comment]
OK, you are right, sorry for that. I will remove it from jforge myselfe and will link you maven repository in my project. No Action is required from you. I can do your thing, release, etc.
